### ISSUE TITLE
UX improvements for influx write

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/influx-cli#78]
__Proposal:__
To support large data imports, `influx write` should have the following improvements:
- [ ] Error handling - failing lines are written out to a log file with the error message, for easy correction and re-importation
- [ ] Error threshold - an import will halt when it reaches a given error-threshold
- [ ] Restart-ability - record its progress through each file and record when it failed or was halted
- [ ] Progress reporting - report on the status of import periodically, with lines imported, lines failed, est. percentage completion, etc.
- [x] Handles compressed files - compressed line protocol or CSV files should be able to be read
- [ ] Respond to standard HTTP errors to throttle uploads dynamically

__Use case:__
These features will make importing very large data sets into Influx much simpler and more robust, helping new customers on-board with less pain.
